TWEAK_NAME = DiaryiPad
DiaryiPad_FILES = Diary.x ../Utils/DRYLocalization.m
DiaryiPad_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
DiaryiPad_FRAMEWORKS = UIKit CoreText CoreTelephony EventKit
DiaryiPad_PRIVATE_FRAMEWORKS = MediaRemote
DiaryiPad_EXTRA_FRAMEWORKS = Cephei
DiaryiPad_LIBRARIES = gcuniversal pddokdo kitten

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
