TWEAK_NAME = DiaryiPhone
DiaryiPhone_FILES = Diary.x ../Utils/DRYLocalization.m
DiaryiPhone_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
DiaryiPhone_FRAMEWORKS = UIKit CoreText CoreTelephony EventKit
DiaryiPhone_PRIVATE_FRAMEWORKS = MediaRemote
DiaryiPhone_EXTRA_FRAMEWORKS = Cephei
DiaryiPhone_LIBRARIES = gcuniversal pddokdo kitten

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
